apiVersion: v1
kind: Service
metadata:
  name: msg-queue-headless
  namespace: msg-queue
  labels:
    app.kubernetes.io/name: msg-queue
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: grpc
      port: 9092
      targetPort: 9092
  selector:
    app.kubernetes.io/name: msg-queue