apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: msg-queue
  namespace: msg-queue
  labels:
    app.kubernetes.io/name: msg-queue
spec:
  serviceName: msg-queue-headless
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: msg-queue
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: msg-queue
    spec:
      serviceAccountName: msg-queue
      containers:
        - name: broker
          image: ghcr.io/testorg/msg-queue:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-config=/config/config.yaml"
          ports:
            - containerPort: 9092
              name: grpc
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /var/lib/msg-queue
      volumes:
        - name: config
          configMap:
            name: msg-queue-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi