apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "msg-queue.name" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "msg-queue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}