replicaCount: 3
image:
  repository: jayabal92/msg-queue
  tag: v1-test
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: ""
service:
  type: ClusterIP
  port: 9092
pdb:
  enabled: true
  minAvailable: 2
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
# storage
persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""
# app config (rendered into ConfigMap)
config:
  server:
    # Unique nodeId per replica — injected via StatefulSet index
    nodeId: "$(POD_NAME)"  
    grpcAddr: "0.0.0.0:9092"   # listen on all interfaces
    httpAddr: "0.0.0.0:8080"

  storage:
    dataDir: "/var/lib/msg-queue"  # PersistentVolume mount
    segmentBytes: 134217728        # 128MiB

  replication:
    rf: 3
    quorumAcks: 2

  etcd:
    endpoints:
      - http://msg-queue-etcd-0.msg-queue-etcd-headless.msg-queue.svc.cluster.local:2379
      - http://msg-queue-etcd-1.msg-queue-etcd-headless.msg-queue.svc.cluster.local:2379
      - http://msg-queue-etcd-2.msg-queue-etcd-headless.msg-queue.svc.cluster.local:2379
    username: ""
    password: ""
    tls:
      enabled: false

etcd:
  replicaCount: 3
  auth:
    rbac:
      create: false
      allowNoneAuthentication: true
      enabled: false
    token:
      enabled: false
    rootPassword: ""
  persistence:
    enabled: true
    size: 2Gi
# extra env
extraEnv: []
# e.g.
# extraEnv:
#   - name: GODEBUG
#     value: madvdontneed=1